CRITICAL - 2024-07-02 08:54:34 --> Undefined variable $bulan
in APPPATH\Controllers\Laporan.php on line 244.
 1 APPPATH\Controllers\Laporan.php(244): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $bulan', 'APPPATH\\Controllers\\Laporan.php', 244)
 2 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Laporan->Tabelabsendivlaporanbulanan()
 3 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Laporan))
 4 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-07-02 08:54:43 --> Undefined variable $bulan
in APPPATH\Controllers\Laporan.php on line 244.
 1 APPPATH\Controllers\Laporan.php(244): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $bulan', 'APPPATH\\Controllers\\Laporan.php', 244)
 2 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Laporan->Tabelabsendivlaporanbulanan()
 3 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Laporan))
 4 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-07-02 08:54:52 --> Undefined variable $bulan
in APPPATH\Controllers\Laporan.php on line 244.
 1 APPPATH\Controllers\Laporan.php(244): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $bulan', 'APPPATH\\Controllers\\Laporan.php', 244)
 2 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Laporan->Tabelabsendivlaporanbulanan()
 3 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Laporan))
 4 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-07-02 08:55:14 --> Undefined variable $bulan
in APPPATH\Controllers\Laporan.php on line 244.
 1 APPPATH\Controllers\Laporan.php(244): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $bulan', 'APPPATH\\Controllers\\Laporan.php', 244)
 2 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Laporan->Tabelabsendivlaporanbulanan()
 3 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Laporan))
 4 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-07-02 09:15:38 --> Trying to access array offset on value of type null
in APPPATH\Views\exim\jurnal\jurnalpembelian\editkurs.php on line 7.
 1 APPPATH\Views\exim\jurnal\jurnalpembelian\editkurs.php(7): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Trying to access array offset on value of type null', 'APPPATH\\Views\\exim\\jurnal\\jurnalpembelian\\editkurs.php', 7)
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\exim\\jurnal\\jurnalpembelian\\editkurs.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('exim/jurnal/jurnalpembelian/editkurs', [], true)
 5 APPPATH\Controllers\exim\Jurnalpembelian.php(136): view('exim/jurnal/jurnalpembelian/editkurs', [...])
 6 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\exim\Jurnalpembelian->Edit()
 7 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\exim\Jurnalpembelian))
 8 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2024-07-02 10:03:54 --> mysqli_sql_exception: Column 'tglinv' in field list is ambiguous in C:\xampp\htdocs\wiharta\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\wiharta\system\Database\MySQLi\Connection.php(292): mysqli->query('SELECT COUNT(*)...', 0)
#1 C:\xampp\htdocs\wiharta\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('SELECT COUNT(*)...')
#2 C:\xampp\htdocs\wiharta\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT COUNT(*)...')
#3 C:\xampp\htdocs\wiharta\system\Database\BaseBuilder.php(1669): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#4 C:\xampp\htdocs\wiharta\system\Model.php(551): CodeIgniter\Database\BaseBuilder->countAllResults(true)
#5 C:\xampp\htdocs\wiharta\app\Models\exim\barangjadi\Exportmutasi_model.php(242): CodeIgniter\Model->countAllResults()
#6 C:\xampp\htdocs\wiharta\app\Controllers\exim\Exportmutasi.php(408): App\Models\exim\barangjadi\Exportmutasi_model->count_allexportmutasi()
#7 C:\xampp\htdocs\wiharta\system\CodeIgniter.php(927): App\Controllers\exim\Exportmutasi->Datatablesexport()
#8 C:\xampp\htdocs\wiharta\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\exim\Exportmutasi))
#9 C:\xampp\htdocs\wiharta\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\wiharta\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}
ERROR - 2024-07-02 10:04:06 --> mysqli_sql_exception: Column 'tglinv' in field list is ambiguous in C:\xampp\htdocs\wiharta\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\wiharta\system\Database\MySQLi\Connection.php(292): mysqli->query('SELECT COUNT(*)...', 0)
#1 C:\xampp\htdocs\wiharta\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('SELECT COUNT(*)...')
#2 C:\xampp\htdocs\wiharta\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT COUNT(*)...')
#3 C:\xampp\htdocs\wiharta\system\Database\BaseBuilder.php(1669): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#4 C:\xampp\htdocs\wiharta\system\Model.php(551): CodeIgniter\Database\BaseBuilder->countAllResults(true)
#5 C:\xampp\htdocs\wiharta\app\Models\exim\barangjadi\Exportmutasi_model.php(242): CodeIgniter\Model->countAllResults()
#6 C:\xampp\htdocs\wiharta\app\Controllers\exim\Exportmutasi.php(408): App\Models\exim\barangjadi\Exportmutasi_model->count_allexportmutasi()
#7 C:\xampp\htdocs\wiharta\system\CodeIgniter.php(927): App\Controllers\exim\Exportmutasi->Datatablesexport()
#8 C:\xampp\htdocs\wiharta\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\exim\Exportmutasi))
#9 C:\xampp\htdocs\wiharta\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\wiharta\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2024-07-02 10:37:58 --> Trying to access array offset on value of type null
in APPPATH\Views\exim\jurnal\jurnalpembelian\editkurs.php on line 7.
 1 APPPATH\Views\exim\jurnal\jurnalpembelian\editkurs.php(7): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Trying to access array offset on value of type null', 'APPPATH\\Views\\exim\\jurnal\\jurnalpembelian\\editkurs.php', 7)
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\exim\\jurnal\\jurnalpembelian\\editkurs.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('exim/jurnal/jurnalpembelian/editkurs', [], true)
 5 APPPATH\Controllers\exim\Jurnalpembelian.php(136): view('exim/jurnal/jurnalpembelian/editkurs', [...])
 6 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\exim\Jurnalpembelian->Edit()
 7 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\exim\Jurnalpembelian))
 8 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-07-02 10:38:29 --> Trying to access array offset on value of type null
in APPPATH\Views\exim\jurnal\jurnalpembelian\editkurs.php on line 7.
 1 APPPATH\Views\exim\jurnal\jurnalpembelian\editkurs.php(7): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Trying to access array offset on value of type null', 'APPPATH\\Views\\exim\\jurnal\\jurnalpembelian\\editkurs.php', 7)
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\exim\\jurnal\\jurnalpembelian\\editkurs.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('exim/jurnal/jurnalpembelian/editkurs', [], true)
 5 APPPATH\Controllers\exim\Jurnalpembelian.php(136): view('exim/jurnal/jurnalpembelian/editkurs', [...])
 6 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\exim\Jurnalpembelian->Edit()
 7 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\exim\Jurnalpembelian))
 8 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-07-02 10:42:30 --> Trying to access array offset on value of type null
in APPPATH\Views\exim\jurnal\jurnalpembelian\editkurs.php on line 7.
 1 APPPATH\Views\exim\jurnal\jurnalpembelian\editkurs.php(7): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Trying to access array offset on value of type null', 'APPPATH\\Views\\exim\\jurnal\\jurnalpembelian\\editkurs.php', 7)
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\exim\\jurnal\\jurnalpembelian\\editkurs.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('exim/jurnal/jurnalpembelian/editkurs', [], true)
 5 APPPATH\Controllers\exim\Jurnalpembelian.php(136): view('exim/jurnal/jurnalpembelian/editkurs', [...])
 6 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\exim\Jurnalpembelian->Edit()
 7 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\exim\Jurnalpembelian))
 8 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2024-07-02 16:11:55 --> mysqli_sql_exception: Unknown column 'beacukai_mutasi_dtl.updated_at' in 'order clause' in C:\xampp\htdocs\wiharta\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\wiharta\system\Database\MySQLi\Connection.php(292): mysqli->query('SELECT `potong_...', 0)
#1 C:\xampp\htdocs\wiharta\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `potong_...')
#2 C:\xampp\htdocs\wiharta\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `potong_...')
#3 C:\xampp\htdocs\wiharta\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT `potong_...', Array, false)
#4 C:\xampp\htdocs\wiharta\app\Models\potong\item\Tipedtl_model.php(68): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\wiharta\app\Controllers\potong\Item.php(95): App\Models\potong\item\Tipedtl_model->get_datatablestipeitem(Array)
#6 C:\xampp\htdocs\wiharta\system\CodeIgniter.php(927): App\Controllers\potong\Item->Datatablestipeitem()
#7 C:\xampp\htdocs\wiharta\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\potong\Item))
#8 C:\xampp\htdocs\wiharta\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\wiharta\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2024-07-02 16:11:55 --> Call to a member function getResult() on bool
in APPPATH\Models\potong\item\Tipedtl_model.php on line 69.
 1 APPPATH\Controllers\potong\Item.php(95): App\Models\potong\item\Tipedtl_model->get_datatablestipeitem([...])
 2 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\potong\Item->Datatablestipeitem()
 3 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\potong\Item))
 4 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-07-02 16:19:59 --> Undefined property: stdClass::$tgl
in APPPATH\Controllers\potong\Item.php on line 101.
 1 APPPATH\Controllers\potong\Item.php(101): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined property: stdClass::$tgl', 'APPPATH\\Controllers\\potong\\Item.php', 101)
 2 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\potong\Item->Datatablestipeitem()
 3 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\potong\Item))
 4 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-07-02 16:20:54 --> Undefined property: stdClass::$no
in APPPATH\Controllers\potong\Item.php on line 101.
 1 APPPATH\Controllers\potong\Item.php(101): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined property: stdClass::$no', 'APPPATH\\Controllers\\potong\\Item.php', 101)
 2 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\potong\Item->Datatablestipeitem()
 3 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\potong\Item))
 4 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-07-02 16:22:18 --> Undefined property: stdClass::$no
in APPPATH\Controllers\potong\Item.php on line 101.
 1 APPPATH\Controllers\potong\Item.php(101): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined property: stdClass::$no', 'APPPATH\\Controllers\\potong\\Item.php', 101)
 2 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\potong\Item->Datatablestipeitem()
 3 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\potong\Item))
 4 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-07-02 16:23:44 --> Undefined property: stdClass::$no
in APPPATH\Controllers\potong\Item.php on line 101.
 1 APPPATH\Controllers\potong\Item.php(101): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined property: stdClass::$no', 'APPPATH\\Controllers\\potong\\Item.php', 101)
 2 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\potong\Item->Datatablestipeitem()
 3 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\potong\Item))
 4 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-07-02 16:39:19 --> Undefined variable $edit
in APPPATH\Views\potong\item\edit.php on line 7.
 1 APPPATH\Views\potong\item\edit.php(7): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $edit', 'APPPATH\\Views\\potong\\item\\edit.php', 7)
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\potong\\item\\edit.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('potong/item/edit', [], true)
 5 APPPATH\Controllers\potong\Item.php(57): view('potong/item/edit', [...])
 6 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\potong\Item->Edit()
 7 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\potong\Item))
 8 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-07-02 17:33:04 --> Undefined array key "namatipe"
in APPPATH\Controllers\potong\Item.php on line 80.
 1 APPPATH\Controllers\potong\Item.php(80): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "namatipe"', 'APPPATH\\Controllers\\potong\\Item.php', 80)
 2 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\potong\Item->Savetipeitem()
 3 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\potong\Item))
 4 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-07-02 17:33:06 --> Undefined array key "namatipe"
in APPPATH\Controllers\potong\Item.php on line 80.
 1 APPPATH\Controllers\potong\Item.php(80): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "namatipe"', 'APPPATH\\Controllers\\potong\\Item.php', 80)
 2 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\potong\Item->Savetipeitem()
 3 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\potong\Item))
 4 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-07-02 17:34:00 --> Undefined array key "namatipe"
in APPPATH\Controllers\potong\Item.php on line 80.
 1 APPPATH\Controllers\potong\Item.php(80): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "namatipe"', 'APPPATH\\Controllers\\potong\\Item.php', 80)
 2 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\potong\Item->Savetipeitem()
 3 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\potong\Item))
 4 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-07-02 17:34:52 --> Undefined array key "namatipe"
in APPPATH\Controllers\potong\Item.php on line 80.
 1 APPPATH\Controllers\potong\Item.php(80): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "namatipe"', 'APPPATH\\Controllers\\potong\\Item.php', 80)
 2 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\potong\Item->Savetipeitem()
 3 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\potong\Item))
 4 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2024-07-02 17:38:28 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in C:\xampp\htdocs\wiharta\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\wiharta\system\Database\MySQLi\Connection.php(292): mysqli->query('UPDATE `potong_...', 0)
#1 C:\xampp\htdocs\wiharta\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `potong_...')
#2 C:\xampp\htdocs\wiharta\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `potong_...')
#3 C:\xampp\htdocs\wiharta\system\Database\BaseBuilder.php(2079): CodeIgniter\Database\BaseConnection->query('UPDATE `potong_...', Array, false)
#4 C:\xampp\htdocs\wiharta\system\Model.php(338): CodeIgniter\Database\BaseBuilder->update()
#5 C:\xampp\htdocs\wiharta\system\BaseModel.php(886): CodeIgniter\Model->doUpdate(NULL, Array)
#6 C:\xampp\htdocs\wiharta\system\Model.php(693): CodeIgniter\BaseModel->update(NULL, Array)
#7 C:\xampp\htdocs\wiharta\app\Controllers\potong\Item.php(83): CodeIgniter\Model->update()
#8 C:\xampp\htdocs\wiharta\system\CodeIgniter.php(927): App\Controllers\potong\Item->Savetipeitem()
#9 C:\xampp\htdocs\wiharta\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\potong\Item))
#10 C:\xampp\htdocs\wiharta\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\wiharta\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
ERROR - 2024-07-02 17:38:30 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in C:\xampp\htdocs\wiharta\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\wiharta\system\Database\MySQLi\Connection.php(292): mysqli->query('UPDATE `potong_...', 0)
#1 C:\xampp\htdocs\wiharta\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `potong_...')
#2 C:\xampp\htdocs\wiharta\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `potong_...')
#3 C:\xampp\htdocs\wiharta\system\Database\BaseBuilder.php(2079): CodeIgniter\Database\BaseConnection->query('UPDATE `potong_...', Array, false)
#4 C:\xampp\htdocs\wiharta\system\Model.php(338): CodeIgniter\Database\BaseBuilder->update()
#5 C:\xampp\htdocs\wiharta\system\BaseModel.php(886): CodeIgniter\Model->doUpdate(NULL, Array)
#6 C:\xampp\htdocs\wiharta\system\Model.php(693): CodeIgniter\BaseModel->update(NULL, Array)
#7 C:\xampp\htdocs\wiharta\app\Controllers\potong\Item.php(83): CodeIgniter\Model->update()
#8 C:\xampp\htdocs\wiharta\system\CodeIgniter.php(927): App\Controllers\potong\Item->Savetipeitem()
#9 C:\xampp\htdocs\wiharta\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\potong\Item))
#10 C:\xampp\htdocs\wiharta\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\wiharta\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
ERROR - 2024-07-02 17:39:42 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in C:\xampp\htdocs\wiharta\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\wiharta\system\Database\MySQLi\Connection.php(292): mysqli->query('UPDATE `potong_...', 0)
#1 C:\xampp\htdocs\wiharta\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `potong_...')
#2 C:\xampp\htdocs\wiharta\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `potong_...')
#3 C:\xampp\htdocs\wiharta\system\Database\BaseBuilder.php(2079): CodeIgniter\Database\BaseConnection->query('UPDATE `potong_...', Array, false)
#4 C:\xampp\htdocs\wiharta\system\Model.php(338): CodeIgniter\Database\BaseBuilder->update()
#5 C:\xampp\htdocs\wiharta\system\BaseModel.php(886): CodeIgniter\Model->doUpdate(NULL, Array)
#6 C:\xampp\htdocs\wiharta\system\Model.php(693): CodeIgniter\BaseModel->update(NULL, Array)
#7 C:\xampp\htdocs\wiharta\app\Controllers\potong\Item.php(83): CodeIgniter\Model->update()
#8 C:\xampp\htdocs\wiharta\system\CodeIgniter.php(927): App\Controllers\potong\Item->Savetipeitem()
#9 C:\xampp\htdocs\wiharta\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\potong\Item))
#10 C:\xampp\htdocs\wiharta\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\wiharta\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
ERROR - 2024-07-02 17:41:47 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in C:\xampp\htdocs\wiharta\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\wiharta\system\Database\MySQLi\Connection.php(292): mysqli->query('UPDATE `potong_...', 0)
#1 C:\xampp\htdocs\wiharta\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `potong_...')
#2 C:\xampp\htdocs\wiharta\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `potong_...')
#3 C:\xampp\htdocs\wiharta\system\Database\BaseBuilder.php(2079): CodeIgniter\Database\BaseConnection->query('UPDATE `potong_...', Array, false)
#4 C:\xampp\htdocs\wiharta\system\Model.php(338): CodeIgniter\Database\BaseBuilder->update()
#5 C:\xampp\htdocs\wiharta\system\BaseModel.php(886): CodeIgniter\Model->doUpdate(NULL, Array)
#6 C:\xampp\htdocs\wiharta\system\Model.php(693): CodeIgniter\BaseModel->update(NULL, Array)
#7 C:\xampp\htdocs\wiharta\app\Controllers\potong\Item.php(83): CodeIgniter\Model->update()
#8 C:\xampp\htdocs\wiharta\system\CodeIgniter.php(927): App\Controllers\potong\Item->Savetipeitem()
#9 C:\xampp\htdocs\wiharta\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\potong\Item))
#10 C:\xampp\htdocs\wiharta\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\wiharta\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
ERROR - 2024-07-02 17:41:51 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in C:\xampp\htdocs\wiharta\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\wiharta\system\Database\MySQLi\Connection.php(292): mysqli->query('UPDATE `potong_...', 0)
#1 C:\xampp\htdocs\wiharta\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `potong_...')
#2 C:\xampp\htdocs\wiharta\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `potong_...')
#3 C:\xampp\htdocs\wiharta\system\Database\BaseBuilder.php(2079): CodeIgniter\Database\BaseConnection->query('UPDATE `potong_...', Array, false)
#4 C:\xampp\htdocs\wiharta\system\Model.php(338): CodeIgniter\Database\BaseBuilder->update()
#5 C:\xampp\htdocs\wiharta\system\BaseModel.php(886): CodeIgniter\Model->doUpdate(NULL, Array)
#6 C:\xampp\htdocs\wiharta\system\Model.php(693): CodeIgniter\BaseModel->update(NULL, Array)
#7 C:\xampp\htdocs\wiharta\app\Controllers\potong\Item.php(83): CodeIgniter\Model->update()
#8 C:\xampp\htdocs\wiharta\system\CodeIgniter.php(927): App\Controllers\potong\Item->Savetipeitem()
#9 C:\xampp\htdocs\wiharta\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\potong\Item))
#10 C:\xampp\htdocs\wiharta\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\wiharta\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
ERROR - 2024-07-02 17:42:10 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in C:\xampp\htdocs\wiharta\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\wiharta\system\Database\MySQLi\Connection.php(292): mysqli->query('UPDATE `potong_...', 0)
#1 C:\xampp\htdocs\wiharta\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `potong_...')
#2 C:\xampp\htdocs\wiharta\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `potong_...')
#3 C:\xampp\htdocs\wiharta\system\Database\BaseBuilder.php(2079): CodeIgniter\Database\BaseConnection->query('UPDATE `potong_...', Array, false)
#4 C:\xampp\htdocs\wiharta\system\Model.php(338): CodeIgniter\Database\BaseBuilder->update()
#5 C:\xampp\htdocs\wiharta\system\BaseModel.php(886): CodeIgniter\Model->doUpdate(NULL, Array)
#6 C:\xampp\htdocs\wiharta\system\Model.php(693): CodeIgniter\BaseModel->update(NULL, Array)
#7 C:\xampp\htdocs\wiharta\app\Controllers\potong\Item.php(83): CodeIgniter\Model->update()
#8 C:\xampp\htdocs\wiharta\system\CodeIgniter.php(927): App\Controllers\potong\Item->Savetipeitem()
#9 C:\xampp\htdocs\wiharta\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\potong\Item))
#10 C:\xampp\htdocs\wiharta\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\wiharta\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
ERROR - 2024-07-02 17:43:39 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in C:\xampp\htdocs\wiharta\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\wiharta\system\Database\MySQLi\Connection.php(292): mysqli->query('UPDATE `potong_...', 0)
#1 C:\xampp\htdocs\wiharta\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `potong_...')
#2 C:\xampp\htdocs\wiharta\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `potong_...')
#3 C:\xampp\htdocs\wiharta\system\Database\BaseBuilder.php(2079): CodeIgniter\Database\BaseConnection->query('UPDATE `potong_...', Array, false)
#4 C:\xampp\htdocs\wiharta\system\Model.php(338): CodeIgniter\Database\BaseBuilder->update()
#5 C:\xampp\htdocs\wiharta\system\BaseModel.php(886): CodeIgniter\Model->doUpdate(NULL, Array)
#6 C:\xampp\htdocs\wiharta\system\Model.php(693): CodeIgniter\BaseModel->update(NULL, Array)
#7 C:\xampp\htdocs\wiharta\app\Controllers\potong\Item.php(83): CodeIgniter\Model->update()
#8 C:\xampp\htdocs\wiharta\system\CodeIgniter.php(927): App\Controllers\potong\Item->Savetipeitem()
#9 C:\xampp\htdocs\wiharta\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\potong\Item))
#10 C:\xampp\htdocs\wiharta\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\wiharta\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
ERROR - 2024-07-02 17:46:13 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in C:\xampp\htdocs\wiharta\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\wiharta\system\Database\MySQLi\Connection.php(292): mysqli->query('UPDATE `potong_...', 0)
#1 C:\xampp\htdocs\wiharta\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `potong_...')
#2 C:\xampp\htdocs\wiharta\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `potong_...')
#3 C:\xampp\htdocs\wiharta\system\Database\BaseBuilder.php(2079): CodeIgniter\Database\BaseConnection->query('UPDATE `potong_...', Array, false)
#4 C:\xampp\htdocs\wiharta\system\Model.php(338): CodeIgniter\Database\BaseBuilder->update()
#5 C:\xampp\htdocs\wiharta\system\BaseModel.php(886): CodeIgniter\Model->doUpdate(NULL, Array)
#6 C:\xampp\htdocs\wiharta\system\Model.php(693): CodeIgniter\BaseModel->update(NULL, Array)
#7 C:\xampp\htdocs\wiharta\app\Controllers\potong\Item.php(83): CodeIgniter\Model->update()
#8 C:\xampp\htdocs\wiharta\system\CodeIgniter.php(927): App\Controllers\potong\Item->Savetipeitem()
#9 C:\xampp\htdocs\wiharta\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\potong\Item))
#10 C:\xampp\htdocs\wiharta\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\wiharta\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
ERROR - 2024-07-02 17:46:14 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in C:\xampp\htdocs\wiharta\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\wiharta\system\Database\MySQLi\Connection.php(292): mysqli->query('UPDATE `potong_...', 0)
#1 C:\xampp\htdocs\wiharta\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `potong_...')
#2 C:\xampp\htdocs\wiharta\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `potong_...')
#3 C:\xampp\htdocs\wiharta\system\Database\BaseBuilder.php(2079): CodeIgniter\Database\BaseConnection->query('UPDATE `potong_...', Array, false)
#4 C:\xampp\htdocs\wiharta\system\Model.php(338): CodeIgniter\Database\BaseBuilder->update()
#5 C:\xampp\htdocs\wiharta\system\BaseModel.php(886): CodeIgniter\Model->doUpdate(NULL, Array)
#6 C:\xampp\htdocs\wiharta\system\Model.php(693): CodeIgniter\BaseModel->update(NULL, Array)
#7 C:\xampp\htdocs\wiharta\app\Controllers\potong\Item.php(83): CodeIgniter\Model->update()
#8 C:\xampp\htdocs\wiharta\system\CodeIgniter.php(927): App\Controllers\potong\Item->Savetipeitem()
#9 C:\xampp\htdocs\wiharta\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\potong\Item))
#10 C:\xampp\htdocs\wiharta\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\wiharta\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
ERROR - 2024-07-02 17:46:14 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in C:\xampp\htdocs\wiharta\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\wiharta\system\Database\MySQLi\Connection.php(292): mysqli->query('UPDATE `potong_...', 0)
#1 C:\xampp\htdocs\wiharta\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `potong_...')
#2 C:\xampp\htdocs\wiharta\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `potong_...')
#3 C:\xampp\htdocs\wiharta\system\Database\BaseBuilder.php(2079): CodeIgniter\Database\BaseConnection->query('UPDATE `potong_...', Array, false)
#4 C:\xampp\htdocs\wiharta\system\Model.php(338): CodeIgniter\Database\BaseBuilder->update()
#5 C:\xampp\htdocs\wiharta\system\BaseModel.php(886): CodeIgniter\Model->doUpdate(NULL, Array)
#6 C:\xampp\htdocs\wiharta\system\Model.php(693): CodeIgniter\BaseModel->update(NULL, Array)
#7 C:\xampp\htdocs\wiharta\app\Controllers\potong\Item.php(83): CodeIgniter\Model->update()
#8 C:\xampp\htdocs\wiharta\system\CodeIgniter.php(927): App\Controllers\potong\Item->Savetipeitem()
#9 C:\xampp\htdocs\wiharta\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\potong\Item))
#10 C:\xampp\htdocs\wiharta\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\wiharta\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
ERROR - 2024-07-02 17:46:19 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in C:\xampp\htdocs\wiharta\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\wiharta\system\Database\MySQLi\Connection.php(292): mysqli->query('UPDATE `potong_...', 0)
#1 C:\xampp\htdocs\wiharta\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `potong_...')
#2 C:\xampp\htdocs\wiharta\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `potong_...')
#3 C:\xampp\htdocs\wiharta\system\Database\BaseBuilder.php(2079): CodeIgniter\Database\BaseConnection->query('UPDATE `potong_...', Array, false)
#4 C:\xampp\htdocs\wiharta\system\Model.php(338): CodeIgniter\Database\BaseBuilder->update()
#5 C:\xampp\htdocs\wiharta\system\BaseModel.php(886): CodeIgniter\Model->doUpdate(NULL, Array)
#6 C:\xampp\htdocs\wiharta\system\Model.php(693): CodeIgniter\BaseModel->update(NULL, Array)
#7 C:\xampp\htdocs\wiharta\app\Controllers\potong\Item.php(83): CodeIgniter\Model->update()
#8 C:\xampp\htdocs\wiharta\system\CodeIgniter.php(927): App\Controllers\potong\Item->Savetipeitem()
#9 C:\xampp\htdocs\wiharta\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\potong\Item))
#10 C:\xampp\htdocs\wiharta\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\wiharta\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
ERROR - 2024-07-02 17:46:20 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in C:\xampp\htdocs\wiharta\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\wiharta\system\Database\MySQLi\Connection.php(292): mysqli->query('UPDATE `potong_...', 0)
#1 C:\xampp\htdocs\wiharta\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `potong_...')
#2 C:\xampp\htdocs\wiharta\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `potong_...')
#3 C:\xampp\htdocs\wiharta\system\Database\BaseBuilder.php(2079): CodeIgniter\Database\BaseConnection->query('UPDATE `potong_...', Array, false)
#4 C:\xampp\htdocs\wiharta\system\Model.php(338): CodeIgniter\Database\BaseBuilder->update()
#5 C:\xampp\htdocs\wiharta\system\BaseModel.php(886): CodeIgniter\Model->doUpdate(NULL, Array)
#6 C:\xampp\htdocs\wiharta\system\Model.php(693): CodeIgniter\BaseModel->update(NULL, Array)
#7 C:\xampp\htdocs\wiharta\app\Controllers\potong\Item.php(83): CodeIgniter\Model->update()
#8 C:\xampp\htdocs\wiharta\system\CodeIgniter.php(927): App\Controllers\potong\Item->Savetipeitem()
#9 C:\xampp\htdocs\wiharta\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\potong\Item))
#10 C:\xampp\htdocs\wiharta\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\wiharta\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
ERROR - 2024-07-02 17:46:26 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in C:\xampp\htdocs\wiharta\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\wiharta\system\Database\MySQLi\Connection.php(292): mysqli->query('UPDATE `potong_...', 0)
#1 C:\xampp\htdocs\wiharta\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `potong_...')
#2 C:\xampp\htdocs\wiharta\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `potong_...')
#3 C:\xampp\htdocs\wiharta\system\Database\BaseBuilder.php(2079): CodeIgniter\Database\BaseConnection->query('UPDATE `potong_...', Array, false)
#4 C:\xampp\htdocs\wiharta\system\Model.php(338): CodeIgniter\Database\BaseBuilder->update()
#5 C:\xampp\htdocs\wiharta\system\BaseModel.php(886): CodeIgniter\Model->doUpdate(NULL, Array)
#6 C:\xampp\htdocs\wiharta\system\Model.php(693): CodeIgniter\BaseModel->update(NULL, Array)
#7 C:\xampp\htdocs\wiharta\app\Controllers\potong\Item.php(83): CodeIgniter\Model->update()
#8 C:\xampp\htdocs\wiharta\system\CodeIgniter.php(927): App\Controllers\potong\Item->Savetipeitem()
#9 C:\xampp\htdocs\wiharta\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\potong\Item))
#10 C:\xampp\htdocs\wiharta\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\wiharta\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
ERROR - 2024-07-02 17:46:27 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in C:\xampp\htdocs\wiharta\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\wiharta\system\Database\MySQLi\Connection.php(292): mysqli->query('UPDATE `potong_...', 0)
#1 C:\xampp\htdocs\wiharta\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `potong_...')
#2 C:\xampp\htdocs\wiharta\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `potong_...')
#3 C:\xampp\htdocs\wiharta\system\Database\BaseBuilder.php(2079): CodeIgniter\Database\BaseConnection->query('UPDATE `potong_...', Array, false)
#4 C:\xampp\htdocs\wiharta\system\Model.php(338): CodeIgniter\Database\BaseBuilder->update()
#5 C:\xampp\htdocs\wiharta\system\BaseModel.php(886): CodeIgniter\Model->doUpdate(NULL, Array)
#6 C:\xampp\htdocs\wiharta\system\Model.php(693): CodeIgniter\BaseModel->update(NULL, Array)
#7 C:\xampp\htdocs\wiharta\app\Controllers\potong\Item.php(83): CodeIgniter\Model->update()
#8 C:\xampp\htdocs\wiharta\system\CodeIgniter.php(927): App\Controllers\potong\Item->Savetipeitem()
#9 C:\xampp\htdocs\wiharta\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\potong\Item))
#10 C:\xampp\htdocs\wiharta\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\wiharta\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
ERROR - 2024-07-02 17:46:55 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in C:\xampp\htdocs\wiharta\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\wiharta\system\Database\MySQLi\Connection.php(292): mysqli->query('UPDATE `potong_...', 0)
#1 C:\xampp\htdocs\wiharta\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `potong_...')
#2 C:\xampp\htdocs\wiharta\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `potong_...')
#3 C:\xampp\htdocs\wiharta\system\Database\BaseBuilder.php(2079): CodeIgniter\Database\BaseConnection->query('UPDATE `potong_...', Array, false)
#4 C:\xampp\htdocs\wiharta\system\Model.php(338): CodeIgniter\Database\BaseBuilder->update()
#5 C:\xampp\htdocs\wiharta\system\BaseModel.php(886): CodeIgniter\Model->doUpdate(NULL, Array)
#6 C:\xampp\htdocs\wiharta\system\Model.php(693): CodeIgniter\BaseModel->update(NULL, Array)
#7 C:\xampp\htdocs\wiharta\app\Controllers\potong\Item.php(83): CodeIgniter\Model->update()
#8 C:\xampp\htdocs\wiharta\system\CodeIgniter.php(927): App\Controllers\potong\Item->Savetipeitem()
#9 C:\xampp\htdocs\wiharta\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\potong\Item))
#10 C:\xampp\htdocs\wiharta\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\wiharta\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
ERROR - 2024-07-02 17:48:11 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in C:\xampp\htdocs\wiharta\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\wiharta\system\Database\MySQLi\Connection.php(292): mysqli->query('UPDATE `potong_...', 0)
#1 C:\xampp\htdocs\wiharta\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `potong_...')
#2 C:\xampp\htdocs\wiharta\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `potong_...')
#3 C:\xampp\htdocs\wiharta\system\Database\BaseBuilder.php(2079): CodeIgniter\Database\BaseConnection->query('UPDATE `potong_...', Array, false)
#4 C:\xampp\htdocs\wiharta\system\Model.php(338): CodeIgniter\Database\BaseBuilder->update()
#5 C:\xampp\htdocs\wiharta\system\BaseModel.php(886): CodeIgniter\Model->doUpdate(NULL, Array)
#6 C:\xampp\htdocs\wiharta\system\Model.php(693): CodeIgniter\BaseModel->update(NULL, Array)
#7 C:\xampp\htdocs\wiharta\app\Controllers\potong\Item.php(83): CodeIgniter\Model->update()
#8 C:\xampp\htdocs\wiharta\system\CodeIgniter.php(927): App\Controllers\potong\Item->Savetipeitem()
#9 C:\xampp\htdocs\wiharta\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\potong\Item))
#10 C:\xampp\htdocs\wiharta\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\wiharta\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
ERROR - 2024-07-02 17:51:40 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in C:\xampp\htdocs\wiharta\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\wiharta\system\Database\MySQLi\Connection.php(292): mysqli->query('UPDATE `potong_...', 0)
#1 C:\xampp\htdocs\wiharta\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `potong_...')
#2 C:\xampp\htdocs\wiharta\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `potong_...')
#3 C:\xampp\htdocs\wiharta\system\Database\BaseBuilder.php(2079): CodeIgniter\Database\BaseConnection->query('UPDATE `potong_...', Array, false)
#4 C:\xampp\htdocs\wiharta\system\Model.php(338): CodeIgniter\Database\BaseBuilder->update()
#5 C:\xampp\htdocs\wiharta\system\BaseModel.php(886): CodeIgniter\Model->doUpdate(NULL, Array)
#6 C:\xampp\htdocs\wiharta\system\Model.php(693): CodeIgniter\BaseModel->update(NULL, Array)
#7 C:\xampp\htdocs\wiharta\app\Controllers\potong\Item.php(83): CodeIgniter\Model->update()
#8 C:\xampp\htdocs\wiharta\system\CodeIgniter.php(927): App\Controllers\potong\Item->Savetipeitem()
#9 C:\xampp\htdocs\wiharta\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\potong\Item))
#10 C:\xampp\htdocs\wiharta\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\wiharta\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
ERROR - 2024-07-02 17:52:33 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in C:\xampp\htdocs\wiharta\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\wiharta\system\Database\MySQLi\Connection.php(292): mysqli->query('UPDATE `potong_...', 0)
#1 C:\xampp\htdocs\wiharta\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `potong_...')
#2 C:\xampp\htdocs\wiharta\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `potong_...')
#3 C:\xampp\htdocs\wiharta\system\Database\BaseBuilder.php(2079): CodeIgniter\Database\BaseConnection->query('UPDATE `potong_...', Array, false)
#4 C:\xampp\htdocs\wiharta\system\Model.php(338): CodeIgniter\Database\BaseBuilder->update()
#5 C:\xampp\htdocs\wiharta\system\BaseModel.php(886): CodeIgniter\Model->doUpdate(NULL, Array)
#6 C:\xampp\htdocs\wiharta\system\Model.php(693): CodeIgniter\BaseModel->update(NULL, Array)
#7 C:\xampp\htdocs\wiharta\app\Controllers\potong\Item.php(83): CodeIgniter\Model->update()
#8 C:\xampp\htdocs\wiharta\system\CodeIgniter.php(927): App\Controllers\potong\Item->Savetipeitem()
#9 C:\xampp\htdocs\wiharta\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\potong\Item))
#10 C:\xampp\htdocs\wiharta\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\wiharta\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
ERROR - 2024-07-02 17:53:03 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in C:\xampp\htdocs\wiharta\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\wiharta\system\Database\MySQLi\Connection.php(292): mysqli->query('UPDATE `potong_...', 0)
#1 C:\xampp\htdocs\wiharta\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `potong_...')
#2 C:\xampp\htdocs\wiharta\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `potong_...')
#3 C:\xampp\htdocs\wiharta\system\Database\BaseBuilder.php(2079): CodeIgniter\Database\BaseConnection->query('UPDATE `potong_...', Array, false)
#4 C:\xampp\htdocs\wiharta\system\Model.php(338): CodeIgniter\Database\BaseBuilder->update()
#5 C:\xampp\htdocs\wiharta\system\BaseModel.php(886): CodeIgniter\Model->doUpdate(NULL, Array)
#6 C:\xampp\htdocs\wiharta\system\Model.php(693): CodeIgniter\BaseModel->update(NULL, Array)
#7 C:\xampp\htdocs\wiharta\app\Controllers\potong\Item.php(83): CodeIgniter\Model->update()
#8 C:\xampp\htdocs\wiharta\system\CodeIgniter.php(927): App\Controllers\potong\Item->Savetipeitem()
#9 C:\xampp\htdocs\wiharta\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\potong\Item))
#10 C:\xampp\htdocs\wiharta\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\wiharta\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
ERROR - 2024-07-02 17:55:45 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in C:\xampp\htdocs\wiharta\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\wiharta\system\Database\MySQLi\Connection.php(292): mysqli->query('UPDATE `potong_...', 0)
#1 C:\xampp\htdocs\wiharta\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `potong_...')
#2 C:\xampp\htdocs\wiharta\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `potong_...')
#3 C:\xampp\htdocs\wiharta\system\Database\BaseBuilder.php(2079): CodeIgniter\Database\BaseConnection->query('UPDATE `potong_...', Array, false)
#4 C:\xampp\htdocs\wiharta\system\Model.php(338): CodeIgniter\Database\BaseBuilder->update()
#5 C:\xampp\htdocs\wiharta\system\BaseModel.php(886): CodeIgniter\Model->doUpdate(NULL, Array)
#6 C:\xampp\htdocs\wiharta\system\Model.php(693): CodeIgniter\BaseModel->update(NULL, Array)
#7 C:\xampp\htdocs\wiharta\app\Controllers\potong\Item.php(83): CodeIgniter\Model->update()
#8 C:\xampp\htdocs\wiharta\system\CodeIgniter.php(927): App\Controllers\potong\Item->Savetipeitem()
#9 C:\xampp\htdocs\wiharta\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\potong\Item))
#10 C:\xampp\htdocs\wiharta\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\wiharta\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
ERROR - 2024-07-02 17:55:53 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in C:\xampp\htdocs\wiharta\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\wiharta\system\Database\MySQLi\Connection.php(292): mysqli->query('UPDATE `potong_...', 0)
#1 C:\xampp\htdocs\wiharta\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `potong_...')
#2 C:\xampp\htdocs\wiharta\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `potong_...')
#3 C:\xampp\htdocs\wiharta\system\Database\BaseBuilder.php(2079): CodeIgniter\Database\BaseConnection->query('UPDATE `potong_...', Array, false)
#4 C:\xampp\htdocs\wiharta\system\Model.php(338): CodeIgniter\Database\BaseBuilder->update()
#5 C:\xampp\htdocs\wiharta\system\BaseModel.php(886): CodeIgniter\Model->doUpdate(NULL, Array)
#6 C:\xampp\htdocs\wiharta\system\Model.php(693): CodeIgniter\BaseModel->update(NULL, Array)
#7 C:\xampp\htdocs\wiharta\app\Controllers\potong\Item.php(83): CodeIgniter\Model->update()
#8 C:\xampp\htdocs\wiharta\system\CodeIgniter.php(927): App\Controllers\potong\Item->Savetipeitem()
#9 C:\xampp\htdocs\wiharta\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\potong\Item))
#10 C:\xampp\htdocs\wiharta\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\wiharta\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2024-07-02 17:57:21 --> There is no data to update.
in SYSTEMPATH\BaseModel.php on line 1598.
 1 SYSTEMPATH\BaseModel.php(1598): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
 2 SYSTEMPATH\BaseModel.php(853): CodeIgniter\BaseModel->transformDataToArray(null, 'update')
 3 SYSTEMPATH\Model.php(693): CodeIgniter\BaseModel->update([...], null)
 4 APPPATH\Controllers\potong\Item.php(83): CodeIgniter\Model->update([...])
 5 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\potong\Item->Savetipeitem()
 6 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\potong\Item))
 7 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2024-07-02 17:59:58 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in C:\xampp\htdocs\wiharta\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\wiharta\system\Database\MySQLi\Connection.php(292): mysqli->query('UPDATE `potong_...', 0)
#1 C:\xampp\htdocs\wiharta\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `potong_...')
#2 C:\xampp\htdocs\wiharta\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `potong_...')
#3 C:\xampp\htdocs\wiharta\system\Database\BaseBuilder.php(2079): CodeIgniter\Database\BaseConnection->query('UPDATE `potong_...', Array, false)
#4 C:\xampp\htdocs\wiharta\system\Model.php(338): CodeIgniter\Database\BaseBuilder->update()
#5 C:\xampp\htdocs\wiharta\system\BaseModel.php(886): CodeIgniter\Model->doUpdate(NULL, Array)
#6 C:\xampp\htdocs\wiharta\system\Model.php(693): CodeIgniter\BaseModel->update(NULL, Array)
#7 C:\xampp\htdocs\wiharta\app\Controllers\potong\Item.php(83): CodeIgniter\Model->update()
#8 C:\xampp\htdocs\wiharta\system\CodeIgniter.php(927): App\Controllers\potong\Item->Savetipeitem()
#9 C:\xampp\htdocs\wiharta\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\potong\Item))
#10 C:\xampp\htdocs\wiharta\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\wiharta\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
ERROR - 2024-07-02 18:00:11 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in C:\xampp\htdocs\wiharta\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\wiharta\system\Database\MySQLi\Connection.php(292): mysqli->query('UPDATE `potong_...', 0)
#1 C:\xampp\htdocs\wiharta\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `potong_...')
#2 C:\xampp\htdocs\wiharta\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `potong_...')
#3 C:\xampp\htdocs\wiharta\system\Database\BaseBuilder.php(2079): CodeIgniter\Database\BaseConnection->query('UPDATE `potong_...', Array, false)
#4 C:\xampp\htdocs\wiharta\system\Model.php(338): CodeIgniter\Database\BaseBuilder->update()
#5 C:\xampp\htdocs\wiharta\system\BaseModel.php(886): CodeIgniter\Model->doUpdate(NULL, Array)
#6 C:\xampp\htdocs\wiharta\system\Model.php(693): CodeIgniter\BaseModel->update(NULL, Array)
#7 C:\xampp\htdocs\wiharta\app\Controllers\potong\Item.php(83): CodeIgniter\Model->update()
#8 C:\xampp\htdocs\wiharta\system\CodeIgniter.php(927): App\Controllers\potong\Item->Savetipeitem()
#9 C:\xampp\htdocs\wiharta\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\potong\Item))
#10 C:\xampp\htdocs\wiharta\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\wiharta\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
ERROR - 2024-07-02 18:00:19 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in C:\xampp\htdocs\wiharta\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\wiharta\system\Database\MySQLi\Connection.php(292): mysqli->query('UPDATE `potong_...', 0)
#1 C:\xampp\htdocs\wiharta\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `potong_...')
#2 C:\xampp\htdocs\wiharta\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `potong_...')
#3 C:\xampp\htdocs\wiharta\system\Database\BaseBuilder.php(2079): CodeIgniter\Database\BaseConnection->query('UPDATE `potong_...', Array, false)
#4 C:\xampp\htdocs\wiharta\system\Model.php(338): CodeIgniter\Database\BaseBuilder->update()
#5 C:\xampp\htdocs\wiharta\system\BaseModel.php(886): CodeIgniter\Model->doUpdate(NULL, Array)
#6 C:\xampp\htdocs\wiharta\system\Model.php(693): CodeIgniter\BaseModel->update(NULL, Array)
#7 C:\xampp\htdocs\wiharta\app\Controllers\potong\Item.php(83): CodeIgniter\Model->update()
#8 C:\xampp\htdocs\wiharta\system\CodeIgniter.php(927): App\Controllers\potong\Item->Savetipeitem()
#9 C:\xampp\htdocs\wiharta\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\potong\Item))
#10 C:\xampp\htdocs\wiharta\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\wiharta\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
ERROR - 2024-07-02 22:39:58 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in C:\xampp\htdocs\wiharta\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\wiharta\system\Database\MySQLi\Connection.php(292): mysqli->query('UPDATE `potong_...', 0)
#1 C:\xampp\htdocs\wiharta\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `potong_...')
#2 C:\xampp\htdocs\wiharta\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `potong_...')
#3 C:\xampp\htdocs\wiharta\system\Database\BaseBuilder.php(2079): CodeIgniter\Database\BaseConnection->query('UPDATE `potong_...', Array, false)
#4 C:\xampp\htdocs\wiharta\system\Model.php(338): CodeIgniter\Database\BaseBuilder->update()
#5 C:\xampp\htdocs\wiharta\system\BaseModel.php(886): CodeIgniter\Model->doUpdate(NULL, Array)
#6 C:\xampp\htdocs\wiharta\system\Model.php(693): CodeIgniter\BaseModel->update(NULL, Array)
#7 C:\xampp\htdocs\wiharta\app\Controllers\potong\Item.php(85): CodeIgniter\Model->update()
#8 C:\xampp\htdocs\wiharta\system\CodeIgniter.php(927): App\Controllers\potong\Item->Savetipeitem()
#9 C:\xampp\htdocs\wiharta\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\potong\Item))
#10 C:\xampp\htdocs\wiharta\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\wiharta\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
ERROR - 2024-07-02 22:40:07 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in C:\xampp\htdocs\wiharta\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\wiharta\system\Database\MySQLi\Connection.php(292): mysqli->query('UPDATE `potong_...', 0)
#1 C:\xampp\htdocs\wiharta\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `potong_...')
#2 C:\xampp\htdocs\wiharta\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `potong_...')
#3 C:\xampp\htdocs\wiharta\system\Database\BaseBuilder.php(2079): CodeIgniter\Database\BaseConnection->query('UPDATE `potong_...', Array, false)
#4 C:\xampp\htdocs\wiharta\system\Model.php(338): CodeIgniter\Database\BaseBuilder->update()
#5 C:\xampp\htdocs\wiharta\system\BaseModel.php(886): CodeIgniter\Model->doUpdate(NULL, Array)
#6 C:\xampp\htdocs\wiharta\system\Model.php(693): CodeIgniter\BaseModel->update(NULL, Array)
#7 C:\xampp\htdocs\wiharta\app\Controllers\potong\Item.php(85): CodeIgniter\Model->update()
#8 C:\xampp\htdocs\wiharta\system\CodeIgniter.php(927): App\Controllers\potong\Item->Savetipeitem()
#9 C:\xampp\htdocs\wiharta\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\potong\Item))
#10 C:\xampp\htdocs\wiharta\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\wiharta\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2024-07-02 23:01:40 --> Undefined array key "use"
in APPPATH\Views\potong\item\edit.php on line 25.
 1 APPPATH\Views\potong\item\edit.php(25): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "use"', 'APPPATH\\Views\\potong\\item\\edit.php', 25)
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\potong\\item\\edit.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('potong/item/edit', [], true)
 5 APPPATH\Controllers\potong\Item.php(57): view('potong/item/edit', [...])
 6 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\potong\Item->Edit()
 7 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\potong\Item))
 8 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
